import type { CareerPackDef } from './types'

const WORLD = 'Ironhaven Miners'
const RIVAL = 'Cascade City Tide'

export const baseballPack: CareerPackDef = {
  id: 'baseball_player',
  label: 'Baseball Player',
  emoji: '⚾',
  roleOptions: ['Pitcher', 'Outfielder', 'Infielder', 'Catcher'],
  orgLabel: 'Team',
  worldName: WORLD,
  rivalWorldName: RIVAL,
  ratingKeys: ['batting', 'pitching', 'fielding', 'speed', 'power', 'arm_strength'],
  defaultRatings: { batting: 76, pitching: 60, fielding: 72, speed: 70, power: 78, arm_strength: 68 },
  bioTemplate: (role, org) => `${role} @ ${org}`,

  npcs: [
    {
      id: 'npc_diego',
      username: 'diegomora',
      displayName: 'Diego Mora',
      bio: `Infielder @ ${WORLD}. Glove first, questions later.`,
      persona: 'teammate',
      personality: ['loyal', 'jokester'],
      verified: true,
      followers: 300_000,
      following: 240,
      postingStyle: { emoji: 0.7, caps: 0.2, hashtags: 0.3 },
    },
    {
      id: 'npc_sam',
      username: 'samwhitfield',
      displayName: 'Sam Whitfield',
      bio: `Captain, catcher, ${WORLD}. Coffee before batting practice.`,
      persona: 'teammate',
      personality: ['calm', 'mentor'],
      verified: true,
      followers: 540_000,
      following: 130,
      postingStyle: { emoji: 0.2, caps: 0.05, hashtags: 0.1 },
    },
    {
      id: 'npc_dobbs',
      username: 'coachdobbs',
      displayName: 'Hank Dobbs',
      bio: `Manager, ${WORLD}. Results business.`,
      persona: 'coach',
      personality: ['stern', 'old_school'],
      verified: true,
      followers: 175_000,
      following: 10,
      postingStyle: { emoji: 0, caps: 0.1, hashtags: 0.05 },
    },
    {
      id: 'npc_colt',
      username: 'coltbishop',
      displayName: 'Colt Bishop',
      bio: `${RIVAL}. Not sorry.`,
      persona: 'rival',
      personality: ['cocky', 'sarcastic'],
      verified: true,
      followers: 560_000,
      following: 70,
      postingStyle: { emoji: 0.3, caps: 0.4, hashtags: 0.2 },
    },
    {
      id: 'npc_renata',
      username: 'renatasilva_agency',
      displayName: 'Renata Silva',
      bio: 'Sports agent. Deals, not drama. (mostly)',
      persona: 'agent',
      personality: ['sharp', 'discreet'],
      verified: true,
      followers: 89_000,
      following: 470,
      postingStyle: { emoji: 0.1, caps: 0, hashtags: 0.05 },
    },
    {
      id: 'npc_fan_miners',
      username: 'minersforlife',
      displayName: 'Miners For Life',
      bio: "Season ticket since the new park opened. Let's dig!",
      persona: 'loyal_fan',
      personality: ['passionate', 'optimistic'],
      verified: false,
      followers: 2_800,
      following: 760,
      postingStyle: { emoji: 0.8, caps: 0.5, hashtags: 0.6 },
    },
    {
      id: 'npc_hater_ump',
      username: 'armchairump',
      displayName: 'Armchair Ump',
      bio: 'Someone has to say it.',
      persona: 'hater',
      personality: ['blunt', 'contrarian'],
      verified: false,
      followers: 7_100,
      following: 980,
      postingStyle: { emoji: 0.2, caps: 0.6, hashtags: 0.3 },
    },
    {
      id: 'npc_meme_diamond',
      username: 'diamondmemes',
      displayName: 'Diamond Memes',
      bio: "Not affiliated with anyone. Please don't sue.",
      persona: 'meme_account',
      personality: ['irreverent', 'quick'],
      verified: true,
      followers: 1_100_000,
      following: 3,
      postingStyle: { emoji: 0.9, caps: 0.3, hashtags: 0.7 },
    },
    {
      id: 'npc_owen',
      username: 'boxscore_owen',
      displayName: 'Owen Baxter',
      bio: 'Writer, The Box Score. Views mine.',
      persona: 'match_reporter',
      personality: ['measured', 'thorough'],
      verified: true,
      followers: 149_000,
      following: 610,
      postingStyle: { emoji: 0.05, caps: 0, hashtags: 0.2 },
    },
    {
      id: 'npc_dugout',
      username: 'dugoutreport',
      displayName: 'The Dugout Report',
      bio: 'Trade news you can trust. Here we go ⚾',
      persona: 'insider',
      personality: ['confident', 'dramatic'],
      verified: true,
      followers: 1_650_000,
      following: 25,
      postingStyle: { emoji: 0.4, caps: 0.1, hashtags: 0.1 },
    },
    {
      id: 'npc_foulball',
      username: 'foulballweekly',
      displayName: 'Foul Ball Weekly',
      bio: 'Where baseball meets everything else.',
      persona: 'tabloid',
      personality: ['nosy', 'gleeful'],
      verified: true,
      followers: 760_000,
      following: 12,
      postingStyle: { emoji: 0.5, caps: 0.3, hashtags: 0.4 },
    },
  ],

  seedPostPool: {
    teammate: [
      'Good round of BP today, barrels flying.',
      'Recovery day. Legs are gone 💀',
      'Big win at the weekend series, onto the next one.',
      `Can't wait for the homestand. Let's go {org}.`,
      'Extra reps in the cage tonight with the boss watching. No days off.',
    ],
    coach: [
      'Focused week of preparation ahead of the series.',
      'Pleased with the intensity in practice. High standards, always.',
      'Roster news later in the week. Everyone is fighting for a spot.',
      'One game at a time. That is all that matters.',
    ],
    rival: [
      'Funny how quiet {org} fans go after a result like that.',
      'Big performance from me today, as usual.',
      'See you all soon. Bring your best.',
      'Some people talk. I just play.',
    ],
    agent: [
      'Productive meetings today. More to follow in due course.',
      'Proud of my clients this week. Hard work pays off.',
      'No comment on the rumours. As always.',
    ],
    loyal_fan: [
      'LETS GO {org_upper}!!! ⚾🔥',
      'Cannot wait for the homestand, absolutely buzzing',
      'Been supporting this team since the new park opened, love this squad ❤️',
      'We are NOT losing this series, I can feel it',
      'Game day energy is unmatched',
    ],
    hater: [
      'Someone has to say it, {org} were lucky again',
      'Overrated roster if you ask me',
      'Not impressed by any of that tbh',
      'Same old story every season',
    ],
    meme_account: [
      'when the cleanup hitter strikes out with bases loaded 💀💀💀 [clip]',
      'nobody: ... baseball twitter at 3am:',
      'this league is actually unwatchable rn 😭',
      'POV: your closer blows the save in the 9th again',
    ],
    match_reporter: [
      'Full analysis of the weekend series out now on The Box Score.',
      'A lineup shift worth watching this week — more in my column.',
      'Injury update expected from the team later today.',
      'Standings looking interesting heading into the weekend.',
    ],
    insider: [
      'Sources close to the team say conversations are ongoing. Nothing imminent. ⚾',
      'Always worth watching this situation. More soon.',
      'Excl: a name to watch ahead of the deadline. Details soon ⏳',
      'Here we go soon on a few deals. Patience.',
    ],
    tabloid: [
      'Spotted: a certain someone out and about last night 👀',
      'The rumour mill is spinning again. Full story on our site.',
      'You will not believe what was said at the after-party.',
      'Sources tell us there is more to this story. Stay tuned.',
    ],
  },

  reactionPool: {
    loyal_fan: {
      generic: [
        'love to see it ❤️',
        'this is why I have your jersey',
        'my player of the season, no debate',
        'lets go {org}!!',
      ],
      byTag: {
        big_moment: ['GET IN {player}!! 🔥', 'that swing was insane', 'never in doubt tbh'],
        huge_moment: ['A GRAND SLAM?! {player} you are UNREAL', 'take a bow. walk-off hero 🐐'],
        loss: ["tough one but we're behind you {player}", 'next series is ours'],
        controversial: ["say what you want, I'm still with you {player}", 'people love to twist things'],
        personal: ['this made my day honestly', 'love this side of you'],
      },
    },
    hater: {
      generic: ['not impressed tbh', 'overrated if you ask me', 'same old story'],
      byTag: {
        loss: ['called it', 'no surprise there'],
        controversial: ['yeah this is exactly the problem with {player}', 'someone had to say it'],
        humble_brag: ['ok we get it, you went yard', 'the ego on this guy'],
      },
    },
    rival: {
      generic: ['cute post', 'anyway back to the cage', 'see you soon {player} 😉'],
      byTag: {
        rivalry: [`can't wait for this series {player}`, 'talk is cheap'],
        win: ['enjoy it while it lasts', 'lucky day for you'],
        controversial: ['this you? 👀', 'no comment... actually one comment'],
      },
    },
    teammate: {
      generic: ['🐐🐐🐐', 'love you brother', 'this team is different this year'],
      byTag: {
        big_moment: ['RBI king behind that one 😏', 'take a bow bro'],
        huge_moment: ['GRAND SLAM HERO. absolute joke', "can't believe what I just watched"],
        training: ['grinding never stops 💪', 'see you in the cage tomorrow'],
        thanks: ['love you too brother', 'this team is a family'],
      },
    },
    coach: {
      generic: ['Good focus this week.', 'Keep your head down and keep working.'],
      byTag: {
        big_moment: ['Clinical at-bat. Pleased with that.', 'Good swing decisions today.'],
        training: ['That is the standard I expect every day.'],
      },
    },
    agent: {
      generic: ['Proud of you.', 'Let the game do the talking.'],
      byTag: {
        deal: ['No comment on the specifics, but watch this space.'],
        rumor: ['We will address speculation through the right channels.'],
      },
    },
    meme_account: {
      generic: ['screenshotting this 📸', 'baseball twitter in shambles rn', 'the timeline is not ready for this'],
      byTag: {
        big_moment: ['{player} really said "watch this" 💀', 'ratio incoming for anyone who disagrees'],
        loss: ['this fanbase rn: 💀', 'the replies are NOT kind'],
        controversial: ['grab the popcorn 🍿', 'this is going to be a whole thing'],
      },
    },
    match_reporter: {
      generic: ['Noted for the box score.', 'Will have more analysis on this shortly.'],
      byTag: {
        big_moment: ['That swing will be replayed on highlight shows for weeks.'],
        huge_moment: ['A performance that deserves real recognition. Full report incoming.'],
        setback: ['Will follow up with the team for an official update on this.'],
      },
    },
    insider: {
      generic: ['Watching this space. 👀', 'More on this soon.'],
      byTag: {
        rumor: ['Sources say this is worth monitoring closely. ⚾'],
        deal: ['Talks are said to be at an early stage. Nothing concrete yet.'],
      },
    },
    tabloid: {
      generic: ['the DMs are FLOODED after this one', 'you will not believe the reaction to this'],
      byTag: {
        party: ['spotted 👀 more photos on our site', 'the night out that has everyone talking'],
        controversial: ['the internet has thoughts and we have receipts', 'this aged... interestingly'],
        relationship: ['well well well 👀', 'the rumour mill just got louder'],
      },
    },
  },

  keywordRules: [
    { tag: 'huge_moment', patterns: [/grand slam/i, /walk[- ]off/i, /perfect game/i, /no[- ]hitter/i] },
    { tag: 'big_moment', patterns: [/home ?run/i, /homered/i, /\bhomer\b/i, /\bRBI\b/i] },
    { tag: 'win', patterns: [/\bwon\b/i, /\bwin\b/i, /\bvictory\b/i] },
    { tag: 'loss', patterns: [/\blost\b/i, /\bloss\b/i, /\bdefeat/i] },
    { tag: 'rivalry', patterns: [/\brivalry\b/i, /\brivals?\b/i] },
    { tag: 'setback', patterns: [/\binjur/i, /disabled list/i, /\bDL\b/, /ruled out/i] },
    { tag: 'rumor', patterns: [/\btraded?\b/i, /free agency/i] },
    { tag: 'deal', patterns: [/\bcontract\b/i, /\bsigned\b/i, /\bextension\b/i] },
    { tag: 'criticism', patterns: [/\bumpire\b/i, /\bump\b/i, /replay review/i] },
    { tag: 'party', patterns: [/\bparty\b/i, /\bnight out\b/i, /\bclub\b/i] },
    { tag: 'relationship', patterns: [/\bgirlfriend\b/i, /\bboyfriend\b/i, /\bengaged\b/i, /\bmarried\b/i] },
    { tag: 'apology', patterns: [/\bsorry\b/i, /\bapolog/i] },
    { tag: 'gratitude', patterns: [/\bthank/i, /\bblessed\b/i, /\bgrateful\b/i, /\bproud\b/i] },
    { tag: 'controversial', patterns: [/\bangry\b/i, /\bfurious\b/i, /\bdisgust/i, /\bdisrespect/i] },
  ],
}
