import type { CareerPack } from './types'

const WORLD = 'Ashcombe United'
const RIVAL = 'Duncastle Rovers'

export const footballerPack: CareerPack = {
  id: 'footballer',
  label: 'Footballer',
  emoji: '⚽',
  roleOptions: ['Forward', 'Midfielder', 'Defender', 'Goalkeeper'],
  orgLabel: 'Club',
  worldName: WORLD,
  rivalWorldName: RIVAL,
  ratingKeys: ['finishing', 'passing', 'pace', 'dribbling', 'physical', 'defending'],
  defaultRatings: { finishing: 78, passing: 68, pace: 82, dribbling: 75, physical: 70, defending: 40 },
  bioTemplate: (role, org) => `${role} @ ${org}`,

  npcs: [
    {
      id: 'npc_jamie',
      username: 'jamie_osei9',
      displayName: 'Jamie Osei',
      bio: `Striker @ ${WORLD}. Left foot is a rumour.`,
      persona: 'teammate',
      personality: ['loyal', 'jokester'],
      verified: true,
      followers: 412_000,
      following: 310,
      postingStyle: { emoji: 0.7, caps: 0.2, hashtags: 0.3 },
    },
    {
      id: 'npc_luca',
      username: 'lucaferreira',
      displayName: 'Luca Ferreira',
      bio: `Captain, ${WORLD}. Father of two. Coffee snob.`,
      persona: 'teammate',
      personality: ['calm', 'mentor'],
      verified: true,
      followers: 890_000,
      following: 145,
      postingStyle: { emoji: 0.2, caps: 0.05, hashtags: 0.1 },
    },
    {
      id: 'npc_wilcox',
      username: 'coachwilcox',
      displayName: 'Terry Wilcox',
      bio: `Manager, ${WORLD}. Results business.`,
      persona: 'coach',
      personality: ['stern', 'old_school'],
      verified: true,
      followers: 210_000,
      following: 12,
      postingStyle: { emoji: 0, caps: 0.1, hashtags: 0.05 },
    },
    {
      id: 'npc_dean',
      username: 'deanrourke',
      displayName: 'Dean Rourke',
      bio: `Striker, ${RIVAL}. Not sorry.`,
      persona: 'rival',
      personality: ['cocky', 'sarcastic'],
      verified: true,
      followers: 655_000,
      following: 88,
      postingStyle: { emoji: 0.3, caps: 0.4, hashtags: 0.2 },
    },
    {
      id: 'npc_priya',
      username: 'priyashah_agency',
      displayName: 'Priya Shah',
      bio: 'Football agent. Deals, not drama. (mostly)',
      persona: 'agent',
      personality: ['sharp', 'discreet'],
      verified: true,
      followers: 98_000,
      following: 540,
      postingStyle: { emoji: 0.1, caps: 0, hashtags: 0.05 },
    },
    {
      id: 'npc_fan_ash',
      username: 'ashcombe4life',
      displayName: "Ashcombe 'Til I Die",
      bio: "Season ticket since '04. Up the Ash!",
      persona: 'loyal_fan',
      personality: ['passionate', 'optimistic'],
      verified: false,
      followers: 3_200,
      following: 890,
      postingStyle: { emoji: 0.8, caps: 0.5, hashtags: 0.6 },
    },
    {
      id: 'npc_hater_ronnie',
      username: 'refwatchronnie',
      displayName: 'Ronnie Blake',
      bio: 'Someone has to say it.',
      persona: 'hater',
      personality: ['blunt', 'contrarian'],
      verified: false,
      followers: 8_700,
      following: 1_200,
      postingStyle: { emoji: 0.2, caps: 0.6, hashtags: 0.3 },
    },
    {
      id: 'npc_meme',
      username: 'footymemesdaily',
      displayName: 'Footy Memes Daily',
      bio: "Not affiliated with anyone. Please don't sue.",
      persona: 'meme_account',
      personality: ['irreverent', 'quick'],
      verified: true,
      followers: 1_450_000,
      following: 4,
      postingStyle: { emoji: 0.9, caps: 0.3, hashtags: 0.7 },
    },
    {
      id: 'npc_nadia',
      username: 'nadiaclarke_sport',
      displayName: 'Nadia Clarke',
      bio: 'Football writer, The Matchday Post. Views mine.',
      persona: 'match_reporter',
      personality: ['measured', 'thorough'],
      verified: true,
      followers: 176_000,
      following: 620,
      postingStyle: { emoji: 0.05, caps: 0, hashtags: 0.2 },
    },
    {
      id: 'npc_enzo',
      username: 'enzobartoli_insider',
      displayName: 'Enzo Bartoli',
      bio: 'Transfer news you can trust. Here we go 🔵',
      persona: 'insider',
      personality: ['confident', 'dramatic'],
      verified: true,
      followers: 2_100_000,
      following: 33,
      postingStyle: { emoji: 0.4, caps: 0.1, hashtags: 0.1 },
    },
    {
      id: 'npc_velvet',
      username: 'velvetropemag',
      displayName: 'The Velvet Rope',
      bio: 'Where football meets everything else.',
      persona: 'tabloid',
      personality: ['nosy', 'gleeful'],
      verified: true,
      followers: 980_000,
      following: 15,
      postingStyle: { emoji: 0.5, caps: 0.3, hashtags: 0.4 },
    },
  ],

  seedPostPool: {
    teammate: [
      'Good session today lads, sharp in the finishing drills.',
      'Recovery day. Legs are gone 💀',
      'Big three points at the weekend, onto the next one.',
      `Can't wait for Saturday. Let's go {org}.`,
      'Extra reps after training with the boss watching. No days off.',
    ],
    coach: [
      'Focused week of preparation ahead of the weekend.',
      'Pleased with the intensity in training. High standards, always.',
      'Squad news later in the week. Everyone is fighting for a shirt.',
      'One game at a time. That is all that matters.',
    ],
    rival: [
      'Funny how quiet {org} fans go after a result like that.',
      'Big performance from me today, as usual.',
      'See you all soon. Bring your best.',
      'Some people talk. I just play.',
    ],
    agent: [
      'Productive meetings today. More to follow in due course.',
      'Proud of my clients this week. Hard work pays off.',
      'No comment on the rumours. As always.',
    ],
    loyal_fan: [
      'UP THE {org_upper}!!! ⚽🔥',
      'Cannot wait for the weekend, absolutely buzzing',
      'Been supporting this club since I was a kid, love this team ❤️',
      'We are NOT losing this one, I can feel it',
      'Matchday energy is unmatched lads',
    ],
    hater: [
      'Someone has to say it, {org} were lucky again',
      'Overrated squad if you ask me',
      'Not impressed by any of that tbh',
      'Same old story every season',
    ],
    meme_account: [
      'when the striker misses an open goal 💀💀💀 [clip]',
      'nobody: ... football twitter at 3am:',
      'this league is actually unwatchable rn 😭',
      'POV: your team concedes in the 90th minute again',
    ],
    match_reporter: [
      'Full analysis of the weekend fixtures out now on The Matchday Post.',
      'A tactical shift worth watching this week — more in my column.',
      'Injury update expected from the club later today.',
      'Form table looking interesting heading into the weekend.',
    ],
    insider: [
      'Sources close to the club say conversations are ongoing. Nothing imminent. 🔵',
      'Always worth watching this situation. More soon.',
      'Excl: a name to watch this window. Details soon ⏳',
      'Here we go soon on a few deals. Patience.',
    ],
    tabloid: [
      'Spotted: a certain someone out and about last night 👀',
      'The rumour mill is spinning again. Full story on our site.',
      'You will not believe what was said at the after-party.',
      'Sources tell us there is more to this story. Stay tuned.',
    ],
  },

  reactionPool: {
    loyal_fan: {
      generic: [
        'love to see it ❤️',
        'this is why I have your shirt',
        'my player of the season, no debate',
        'up the {org}!!',
      ],
      byTag: {
        big_moment: ['GET IN {player}!! 🔥', 'that finish was insane', 'never in doubt tbh'],
        huge_moment: ['A HAT-TRICK?! {player} you are UNREAL', 'take a bow. hat-trick hero 🐐'],
        loss: ["tough one but we're behind you {player}", 'next week is ours'],
        controversial: ["say what you want, I'm still with you {player}", 'people love to twist things'],
        personal: ['this made my day honestly', 'love this side of you'],
      },
    },
    hater: {
      generic: ['not impressed tbh', 'overrated if you ask me', 'same old story'],
      byTag: {
        loss: ['called it', 'no surprise there'],
        controversial: ['yeah this is exactly the problem with {player}', 'someone had to say it'],
        humble_brag: ['ok we get it, you scored', 'the ego on this guy'],
      },
    },
    rival: {
      generic: ['cute post', 'anyway back to training', 'see you soon {player} 😉'],
      byTag: {
        rivalry: [`can't wait for this one {player}`, 'talk is cheap'],
        win: ['enjoy it while it lasts', 'lucky day for you'],
        controversial: ['this you? 👀', 'no comment... actually one comment'],
      },
    },
    teammate: {
      generic: ['🐐🐐🐐', 'love you brother', 'this team is different this year'],
      byTag: {
        big_moment: ['assist king behind that one 😏', 'take a bow bro'],
        huge_moment: ['HAT-TRICK HERO. absolute joke', "can't believe what I just watched"],
        training: ['grinding never stops 💪', 'see you at 9am tomorrow'],
        thanks: ['love you too brother', 'this squad is a family'],
      },
    },
    coach: {
      generic: ['Good focus this week.', 'Keep your head down and keep working.'],
      byTag: {
        big_moment: ['Clinical finishing. Pleased with that.', 'Good movement in the box today.'],
        training: ['That is the standard I expect every day.'],
      },
    },
    agent: {
      generic: ['Proud of you.', 'Let the football do the talking.'],
      byTag: {
        deal: ['No comment on the specifics, but watch this space.'],
        rumor: ['We will address speculation through the right channels.'],
      },
    },
    meme_account: {
      generic: ['screenshotting this 📸', 'football twitter in shambles rn', 'the timeline is not ready for this'],
      byTag: {
        big_moment: ['{player} really said "watch this" 💀', 'ratio incoming for anyone who disagrees'],
        loss: ['this fanbase rn: 💀', 'the replies are NOT kind'],
        controversial: ['grab the popcorn 🍿', 'this is going to be a whole thing'],
      },
    },
    match_reporter: {
      generic: ['Noted for the match report.', 'Will have more analysis on this shortly.'],
      byTag: {
        big_moment: ['That goal will be replayed on highlight shows for weeks.'],
        huge_moment: ['A hat-trick performance that deserves real recognition. Full report incoming.'],
        setback: ['Will follow up with the club for an official update on this.'],
      },
    },
    insider: {
      generic: ['Watching this space. 👀', 'More on this soon.'],
      byTag: {
        rumor: ['Sources say this is worth monitoring closely. 🔵'],
        deal: ['Talks are said to be at an early stage. Nothing concrete yet.'],
      },
    },
    tabloid: {
      generic: ['the DMs are FLOODED after this one', 'you will not believe the reaction to this'],
      byTag: {
        party: ['spotted 👀 more photos on our site', 'the night out that has everyone talking'],
        controversial: ['the internet has thoughts and we have receipts', 'this aged... interestingly'],
        relationship: ['well well well 👀', 'the rumour mill just got louder'],
      },
    },
  },

  keywordRules: [
    { tag: 'huge_moment', patterns: [/hat[\s-]?trick/i] },
    { tag: 'big_moment', patterns: [/\bgoals?\b/i, /\bscored?\b/i, /\bscoring\b/i] },
    { tag: 'win', patterns: [/\bwon\b/i, /\bwin\b/i, /\bvictory\b/i] },
    { tag: 'loss', patterns: [/\blost\b/i, /\bloss\b/i, /\bdefeat/i] },
    { tag: 'rivalry', patterns: [/\bderby\b/i] },
    { tag: 'setback', patterns: [/\binjur/i, /\bruled out\b/i] },
    { tag: 'rumor', patterns: [/\bleav(e|ing)\b/i, /\bexit\b/i, /\btransfer\b/i] },
    { tag: 'deal', patterns: [/\bcontract\b/i, /\bsign(ed|ing)?\b/i, /\bdeal\b/i] },
    { tag: 'criticism', patterns: [/\breferee\b/i, /\bref\b/i, /\bvar\b/i] },
    { tag: 'party', patterns: [/\bparty\b/i, /\bnight out\b/i, /\bclub\b(?!.*united)/i] },
    { tag: 'relationship', patterns: [/\bgirlfriend\b/i, /\bboyfriend\b/i, /\bengaged\b/i, /\bmarried\b/i] },
    { tag: 'apology', patterns: [/\bsorry\b/i, /\bapolog/i] },
    { tag: 'gratitude', patterns: [/\bthank/i, /\bblessed\b/i, /\bgrateful\b/i, /\bproud\b/i] },
    { tag: 'controversial', patterns: [/\bangry\b/i, /\bfurious\b/i, /\bdisgust/i, /\bdisrespect/i] },
  ],
}
