import type { CareerPack } from './types'

const WORLD = 'Nightfall Records'
const RIVAL = 'Chrome City'

export const rapperPack: CareerPack = {
  id: 'rapper',
  label: 'Rapper',
  emoji: '🎤',
  roleOptions: ['MC', 'Rapper-Producer', 'Lyricist'],
  orgLabel: 'Label',
  worldName: WORLD,
  rivalWorldName: RIVAL,
  ratingKeys: ['flow', 'wordplay', 'stage_presence', 'charisma', 'studio_craft', 'hustle'],
  defaultRatings: { flow: 75, wordplay: 80, stage_presence: 70, charisma: 72, studio_craft: 65, hustle: 74 },
  bioTemplate: (role, org) => `${role} @ ${org}`,

  npcs: [
    {
      id: 'npc_ray',
      username: 'raywav',
      displayName: 'Ray Wav',
      bio: `Producer @ ${WORLD}. Beats hit different.`,
      persona: 'teammate',
      personality: ['loyal', 'jokester'],
      verified: true,
      followers: 380_000,
      following: 290,
      postingStyle: { emoji: 0.7, caps: 0.3, hashtags: 0.4 },
    },
    {
      id: 'npc_nova',
      username: 'novareigns',
      displayName: 'Nova Reigns',
      bio: `Labelmate @ ${WORLD}. Two mics, one booth.`,
      persona: 'teammate',
      personality: ['calm', 'mentor'],
      verified: true,
      followers: 720_000,
      following: 140,
      postingStyle: { emoji: 0.3, caps: 0.1, hashtags: 0.2 },
    },
    {
      id: 'npc_gwave',
      username: 'gwave_anr',
      displayName: "Marcus 'G-Wave' Davis",
      bio: `A&R, ${WORLD}. I hear hits before they're hits.`,
      persona: 'coach',
      personality: ['stern', 'old_school'],
      verified: true,
      followers: 195_000,
      following: 20,
      postingStyle: { emoji: 0, caps: 0.1, hashtags: 0.05 },
    },
    {
      id: 'npc_lilchrome',
      username: 'lilchrome',
      displayName: 'Lil Chrome',
      bio: `${RIVAL}. You already know.`,
      persona: 'rival',
      personality: ['cocky', 'sarcastic'],
      verified: true,
      followers: 810_000,
      following: 60,
      postingStyle: { emoji: 0.4, caps: 0.5, hashtags: 0.3 },
    },
    {
      id: 'npc_tasha',
      username: 'tashareyes_mgmt',
      displayName: 'Tasha Reyes',
      bio: 'Talent manager. Deals, not drama. (mostly)',
      persona: 'agent',
      personality: ['sharp', 'discreet'],
      verified: true,
      followers: 112_000,
      following: 460,
      postingStyle: { emoji: 0.1, caps: 0, hashtags: 0.05 },
    },
    {
      id: 'npc_fan_dayone',
      username: 'day1stan',
      displayName: 'Day One 🎧',
      bio: 'Been riding since the mixtape days.',
      persona: 'loyal_fan',
      personality: ['passionate', 'optimistic'],
      verified: false,
      followers: 5_100,
      following: 720,
      postingStyle: { emoji: 0.8, caps: 0.5, hashtags: 0.6 },
    },
    {
      id: 'npc_hater_kev',
      username: 'kevkeepsit100',
      displayName: 'Kev',
      bio: 'Someone has to say it.',
      persona: 'hater',
      personality: ['blunt', 'contrarian'],
      verified: false,
      followers: 9_400,
      following: 1_100,
      postingStyle: { emoji: 0.2, caps: 0.6, hashtags: 0.3 },
    },
    {
      id: 'npc_meme_rap',
      username: 'rapmemevault',
      displayName: 'Rap Meme Vault',
      bio: "Not affiliated with anyone. Please don't sue.",
      persona: 'meme_account',
      personality: ['irreverent', 'quick'],
      verified: true,
      followers: 1_650_000,
      following: 6,
      postingStyle: { emoji: 0.9, caps: 0.3, hashtags: 0.7 },
    },
    {
      id: 'npc_journo',
      username: 'hiphopweekly_dez',
      displayName: 'Dez Okafor',
      bio: 'Writer, Hip-Hop Weekly. Views mine.',
      persona: 'match_reporter',
      personality: ['measured', 'thorough'],
      verified: true,
      followers: 164_000,
      following: 580,
      postingStyle: { emoji: 0.05, caps: 0, hashtags: 0.2 },
    },
    {
      id: 'npc_booth',
      username: 'thebooth_insider',
      displayName: 'The Booth',
      bio: 'Industry news you can trust. Here we go 🎙️',
      persona: 'insider',
      personality: ['confident', 'dramatic'],
      verified: true,
      followers: 1_900_000,
      following: 28,
      postingStyle: { emoji: 0.4, caps: 0.1, hashtags: 0.1 },
    },
    {
      id: 'npc_static',
      username: 'staticblog',
      displayName: 'Static',
      bio: 'Where music meets everything else.',
      persona: 'tabloid',
      personality: ['nosy', 'gleeful'],
      verified: true,
      followers: 890_000,
      following: 18,
      postingStyle: { emoji: 0.5, caps: 0.3, hashtags: 0.4 },
    },
  ],

  seedPostPool: {
    teammate: [
      'Long night in the booth, this one is different.',
      'Off day. Ears are fried from mixing 💀',
      'Big drop this week, onto the next one.',
      `Can't wait for the show. Let's go {org}.`,
      'Extra takes tonight with the boss listening. No days off.',
    ],
    coach: [
      'Focused week ahead of the release.',
      'Pleased with the work ethic in the booth. High standards, always.',
      'News coming later in the week. Everyone is fighting for a verse.',
      'One track at a time. That is all that matters.',
    ],
    rival: [
      'Funny how quiet {org} stans go after a drop like that.',
      'Big performance from me today, as usual.',
      'See you all soon. Bring your best bars.',
      'Some people talk. I just spit.',
    ],
    agent: [
      'Productive meetings today. More to follow in due course.',
      'Proud of my clients this week. Hard work pays off.',
      'No comment on the rumours. As always.',
    ],
    loyal_fan: [
      'RUN IT UP {org_upper}!!! 🎧🔥',
      'Cannot wait for the drop, absolutely buzzing',
      'Been riding since the mixtape days, love this artist ❤️',
      'This one is NOT flopping, I can feel it',
      'Release day energy is unmatched',
    ],
    hater: [
      'Someone has to say it, {org} got lucky with that one',
      'Overrated if you ask me',
      'Not impressed by any of that tbh',
      'Same old flow every album',
    ],
    meme_account: [
      'when the beat drops and the bars dont 💀💀💀 [clip]',
      'nobody: ... rap twitter at 3am:',
      'this scene is actually unlistenable rn 😭',
      'POV: the feature verse outshines the whole song',
    ],
    match_reporter: [
      'Full breakdown of this week in rap out now on Hip-Hop Weekly.',
      'A stylistic shift worth watching this week — more in my column.',
      'Studio update expected from the label later today.',
      'Chart positions looking interesting heading into the weekend.',
    ],
    insider: [
      'Sources close to the label say conversations are ongoing. Nothing imminent. 🎙️',
      'Always worth watching this situation. More soon.',
      'Excl: a name to watch this cycle. Details soon ⏳',
      'Here we go soon on a few features. Patience.',
    ],
    tabloid: [
      'Spotted: a certain someone out and about last night 👀',
      'The rumour mill is spinning again. Full story on our site.',
      'You will not believe what was said at the after-party.',
      'Sources tell us there is more to this story. Stay tuned.',
    ],
  },

  reactionPool: {
    loyal_fan: {
      generic: [
        'love to see it ❤️',
        'this is why I have the merch',
        'my artist of the year, no debate',
        'run it up {org}!!',
      ],
      byTag: {
        big_moment: ['THIS IS THE ONE {player}!! 🔥', 'that hook was insane', 'never in doubt tbh'],
        huge_moment: ['NUMBER ONE?! {player} you are UNREAL', 'take a bow. chart-topper 🐐'],
        loss: ["tough one but we're behind you {player}", 'next drop is ours'],
        controversial: ["say what you want, I'm still with you {player}", 'people love to twist things'],
        personal: ['this made my day honestly', 'love this side of you'],
      },
    },
    hater: {
      generic: ['not impressed tbh', 'overrated if you ask me', 'same old story'],
      byTag: {
        loss: ['called it', 'no surprise there'],
        controversial: ['yeah this is exactly the problem with {player}', 'someone had to say it'],
        humble_brag: ['ok we get it, it charted', 'the ego on this guy'],
      },
    },
    rival: {
      generic: ['cute post', 'anyway back to the booth', 'see you soon {player} 😉'],
      byTag: {
        rivalry: [`can't wait to drop this one {player}`, 'talk is cheap'],
        win: ['enjoy it while it lasts', 'lucky week for you'],
        controversial: ['this you? 👀', 'no comment... actually one comment'],
      },
    },
    teammate: {
      generic: ['🐐🐐🐐', 'love you bro', 'this label is different this year'],
      byTag: {
        big_moment: ['feature king behind that one 😏', 'take a bow bro'],
        huge_moment: ['CHART TOPPER. absolute joke', "can't believe what I just heard"],
        training: ['booth time never stops 💪', 'see you at the studio tomorrow'],
        thanks: ['love you too bro', 'this label is a family'],
      },
    },
    coach: {
      generic: ['Good focus this week.', 'Keep your head down and keep working.'],
      byTag: {
        big_moment: ['Clinical delivery. Pleased with that.', 'Good pocket on that verse today.'],
        training: ['That is the standard I expect every day.'],
      },
    },
    agent: {
      generic: ['Proud of you.', 'Let the music do the talking.'],
      byTag: {
        deal: ['No comment on the specifics, but watch this space.'],
        rumor: ['We will address speculation through the right channels.'],
      },
    },
    meme_account: {
      generic: ['screenshotting this 📸', 'rap twitter in shambles rn', 'the timeline is not ready for this'],
      byTag: {
        big_moment: ['{player} really said "watch this" 💀', 'ratio incoming for anyone who disagrees'],
        loss: ['this fanbase rn: 💀', 'the replies are NOT kind'],
        controversial: ['grab the popcorn 🍿', 'this is going to be a whole thing'],
      },
    },
    match_reporter: {
      generic: ['Noted for the column.', 'Will have more analysis on this shortly.'],
      byTag: {
        big_moment: ['That hook will be replayed on playlists for weeks.'],
        huge_moment: ['A chart-topping run that deserves real recognition. Full piece incoming.'],
        setback: ['Will follow up with the label for an official update on this.'],
      },
    },
    insider: {
      generic: ['Watching this space. 👀', 'More on this soon.'],
      byTag: {
        rumor: ['Sources say this is worth monitoring closely. 🎙️'],
        deal: ['Talks are said to be at an early stage. Nothing concrete yet.'],
      },
    },
    tabloid: {
      generic: ['the DMs are FLOODED after this one', 'you will not believe the reaction to this'],
      byTag: {
        party: ['spotted 👀 more photos on our site', 'the after-party that has everyone talking'],
        controversial: ['the internet has thoughts and we have receipts', 'this aged... interestingly'],
        relationship: ['well well well 👀', 'the rumour mill just got louder'],
      },
    },
  },

  keywordRules: [
    { tag: 'huge_moment', patterns: [/number one/i, /#1\b/i, /triple platinum/i, /diamond/i] },
    { tag: 'big_moment', patterns: [/\bdropped\b/i, /\bplatinum\b/i, /went viral/i, /new single/i, /hit the charts/i] },
    { tag: 'win', patterns: [/\bwon\b/i, /\bvictory\b/i, /topp(ed|ing) the charts/i] },
    { tag: 'loss', patterns: [/\bflopped\b/i, /\bbombed\b/i] },
    { tag: 'rivalry', patterns: [/\bbeef\b/i, /diss track/i, /clapback/i] },
    { tag: 'setback', patterns: [/vocal strain/i, /lost my voice/i, /cancel(l)?ed the tour/i] },
    { tag: 'rumor', patterns: [/leaving the label/i, /signing elsewhere/i, /label switch/i] },
    { tag: 'deal', patterns: [/\bsigned\b/i, /new deal/i, /\bcontract\b/i, /brand deal/i] },
    { tag: 'criticism', patterns: [/\bcritics?\b/i, /\breviewers?\b/i] },
    { tag: 'party', patterns: [/\bparty\b/i, /after[- ]party/i, /\bclub\b/i] },
    { tag: 'relationship', patterns: [/\bgirlfriend\b/i, /\bboyfriend\b/i, /\bengaged\b/i, /\bmarried\b/i] },
    { tag: 'apology', patterns: [/\bsorry\b/i, /\bapolog/i] },
    { tag: 'gratitude', patterns: [/\bthank/i, /\bblessed\b/i, /\bgrateful\b/i, /\bproud\b/i] },
    { tag: 'controversial', patterns: [/\bangry\b/i, /\bfurious\b/i, /\bdisgust/i, /\bdisrespect/i] },
  ],
}
