import type { CareerPack } from './types'

const WORLD = 'Halcyon Music'
const RIVAL = 'Prism Sound'

export const singerPack: CareerPack = {
  id: 'singer',
  label: 'Singer',
  emoji: '🎵',
  roleOptions: ['Pop Singer', 'Vocalist', 'Singer-Songwriter'],
  orgLabel: 'Label',
  worldName: WORLD,
  rivalWorldName: RIVAL,
  ratingKeys: ['vocals', 'stage_presence', 'songwriting', 'charisma', 'range', 'stamina'],
  defaultRatings: { vocals: 80, stage_presence: 75, songwriting: 70, charisma: 74, range: 72, stamina: 68 },
  bioTemplate: (role, org) => `${role} @ ${org}`,

  npcs: [
    {
      id: 'npc_mia',
      username: 'miatorres',
      displayName: 'Mia Torres',
      bio: `Backup vocalist & dancer @ ${WORLD}. Always on beat.`,
      persona: 'teammate',
      personality: ['loyal', 'jokester'],
      verified: true,
      followers: 340_000,
      following: 260,
      postingStyle: { emoji: 0.7, caps: 0.2, hashtags: 0.3 },
    },
    {
      id: 'npc_theo',
      username: 'theolin_writes',
      displayName: 'Theo Lin',
      bio: `Songwriting partner @ ${WORLD}. Melodies before breakfast.`,
      persona: 'teammate',
      personality: ['calm', 'mentor'],
      verified: true,
      followers: 610_000,
      following: 150,
      postingStyle: { emoji: 0.2, caps: 0.05, hashtags: 0.1 },
    },
    {
      id: 'npc_renee',
      username: 'reneeokonkwo',
      displayName: 'Renee Okonkwo',
      bio: `Vocal coach & A&R, ${WORLD}. Results business.`,
      persona: 'coach',
      personality: ['stern', 'old_school'],
      verified: true,
      followers: 188_000,
      following: 14,
      postingStyle: { emoji: 0, caps: 0.1, hashtags: 0.05 },
    },
    {
      id: 'npc_skylar',
      username: 'skylarvex',
      displayName: 'Skylar Vex',
      bio: `${RIVAL}. Not sorry.`,
      persona: 'rival',
      personality: ['cocky', 'sarcastic'],
      verified: true,
      followers: 720_000,
      following: 95,
      postingStyle: { emoji: 0.3, caps: 0.4, hashtags: 0.2 },
    },
    {
      id: 'npc_diane',
      username: 'dianecho_mgmt',
      displayName: 'Diane Cho',
      bio: 'Talent manager. Deals, not drama. (mostly)',
      persona: 'agent',
      personality: ['sharp', 'discreet'],
      verified: true,
      followers: 104_000,
      following: 500,
      postingStyle: { emoji: 0.1, caps: 0, hashtags: 0.05 },
    },
    {
      id: 'npc_fan_tourbus',
      username: 'tourbusstan',
      displayName: 'Tour Bus Stan',
      bio: 'Front row since the first tour. Forever.',
      persona: 'loyal_fan',
      personality: ['passionate', 'optimistic'],
      verified: false,
      followers: 4_600,
      following: 810,
      postingStyle: { emoji: 0.8, caps: 0.5, hashtags: 0.6 },
    },
    {
      id: 'npc_hater_justmy',
      username: 'justmyopinion_',
      displayName: 'Just My Opinion',
      bio: 'Someone has to say it.',
      persona: 'hater',
      personality: ['blunt', 'contrarian'],
      verified: false,
      followers: 7_900,
      following: 1_050,
      postingStyle: { emoji: 0.2, caps: 0.6, hashtags: 0.3 },
    },
    {
      id: 'npc_meme_pop',
      username: 'popmemecentral',
      displayName: 'Pop Meme Central',
      bio: "Not affiliated with anyone. Please don't sue.",
      persona: 'meme_account',
      personality: ['irreverent', 'quick'],
      verified: true,
      followers: 1_520_000,
      following: 5,
      postingStyle: { emoji: 0.9, caps: 0.3, hashtags: 0.7 },
    },
    {
      id: 'npc_sasha',
      username: 'sashavale_melody',
      displayName: 'Sasha Vale',
      bio: 'Music writer, Melody Monthly. Views mine.',
      persona: 'match_reporter',
      personality: ['measured', 'thorough'],
      verified: true,
      followers: 158_000,
      following: 600,
      postingStyle: { emoji: 0.05, caps: 0, hashtags: 0.2 },
    },
    {
      id: 'npc_greenroom',
      username: 'thegreenroom',
      displayName: 'The Green Room',
      bio: 'Industry news you can trust. Here we go 🎶',
      persona: 'insider',
      personality: ['confident', 'dramatic'],
      verified: true,
      followers: 1_780_000,
      following: 30,
      postingStyle: { emoji: 0.4, caps: 0.1, hashtags: 0.1 },
    },
    {
      id: 'npc_spotlight',
      username: 'spotlightweekly',
      displayName: 'Spotlight Weekly',
      bio: 'Where music meets everything else.',
      persona: 'tabloid',
      personality: ['nosy', 'gleeful'],
      verified: true,
      followers: 940_000,
      following: 16,
      postingStyle: { emoji: 0.5, caps: 0.3, hashtags: 0.4 },
    },
  ],

  seedPostPool: {
    teammate: [
      'Long rehearsal today, this set is different.',
      'Off day. Voice needs the rest 💀',
      'Big show this week, onto the next one.',
      `Can't wait for the tour stop. Let's go {org}.`,
      'Extra run-throughs tonight with the boss watching. No days off.',
    ],
    coach: [
      'Focused week ahead of the release.',
      'Pleased with the discipline in rehearsal. High standards, always.',
      'News coming later in the week. Everyone is fighting for the spotlight.',
      'One show at a time. That is all that matters.',
    ],
    rival: [
      'Funny how quiet {org} stans go after a night like that.',
      'Big performance from me today, as usual.',
      'See you all soon. Bring your best.',
      'Some people talk. I just perform.',
    ],
    agent: [
      'Productive meetings today. More to follow in due course.',
      'Proud of my clients this week. Hard work pays off.',
      'No comment on the rumours. As always.',
    ],
    loyal_fan: [
      'RUN IT UP {org_upper}!!! 🎶🔥',
      'Cannot wait for the show, absolutely buzzing',
      'Front row since the first tour, love this artist ❤️',
      'This one is NOT flopping, I can feel it',
      'Show day energy is unmatched',
    ],
    hater: [
      'Someone has to say it, {org} got lucky with that one',
      'Overrated if you ask me',
      'Not impressed by any of that tbh',
      'Same old sound every album',
    ],
    meme_account: [
      'when the high note doesnt land 💀💀💀 [clip]',
      'nobody: ... pop twitter at 3am:',
      'this scene is actually unlistenable rn 😭',
      'POV: the opening act outshines the headliner',
    ],
    match_reporter: [
      'Full breakdown of this week in pop out now on Melody Monthly.',
      'A stylistic shift worth watching this week — more in my column.',
      'Rehearsal update expected from the label later today.',
      'Chart positions looking interesting heading into the weekend.',
    ],
    insider: [
      'Sources close to the label say conversations are ongoing. Nothing imminent. 🎶',
      'Always worth watching this situation. More soon.',
      'Excl: a name to watch this cycle. Details soon ⏳',
      'Here we go soon on a few collabs. Patience.',
    ],
    tabloid: [
      'Spotted: a certain someone out and about last night 👀',
      'The rumour mill is spinning again. Full story on our site.',
      'You will not believe what was said at the after-party.',
      'Sources tell us there is more to this story. Stay tuned.',
    ],
  },

  reactionPool: {
    loyal_fan: {
      generic: [
        'love to see it ❤️',
        'this is why I have the tour merch',
        'my artist of the year, no debate',
        'run it up {org}!!',
      ],
      byTag: {
        big_moment: ['THIS IS THE ONE {player}!! 🔥', 'that chorus was insane', 'never in doubt tbh'],
        huge_moment: ['NUMBER ONE?! {player} you are UNREAL', 'take a bow. chart-topper 🐐'],
        loss: ["tough one but we're behind you {player}", 'next release is ours'],
        controversial: ["say what you want, I'm still with you {player}", 'people love to twist things'],
        personal: ['this made my day honestly', 'love this side of you'],
      },
    },
    hater: {
      generic: ['not impressed tbh', 'overrated if you ask me', 'same old story'],
      byTag: {
        loss: ['called it', 'no surprise there'],
        controversial: ['yeah this is exactly the problem with {player}', 'someone had to say it'],
        humble_brag: ['ok we get it, it charted', 'the ego on this one'],
      },
    },
    rival: {
      generic: ['cute post', 'anyway back to rehearsal', 'see you soon {player} 😉'],
      byTag: {
        rivalry: [`can't wait for this one {player}`, 'talk is cheap'],
        win: ['enjoy it while it lasts', 'lucky week for you'],
        controversial: ['this you? 👀', 'no comment... actually one comment'],
      },
    },
    teammate: {
      generic: ['🐐🐐🐐', 'love you', 'this label is different this year'],
      byTag: {
        big_moment: ['runner-up energy behind that one 😏', 'take a bow'],
        huge_moment: ['CHART TOPPER. absolute joke', "can't believe what I just heard"],
        training: ['rehearsal never stops 💪', 'see you at soundcheck tomorrow'],
        thanks: ['love you too', 'this label is a family'],
      },
    },
    coach: {
      generic: ['Good focus this week.', 'Keep your head down and keep working.'],
      byTag: {
        big_moment: ['Clinical delivery. Pleased with that.', 'Good control on that run today.'],
        training: ['That is the standard I expect every day.'],
      },
    },
    agent: {
      generic: ['Proud of you.', 'Let the music do the talking.'],
      byTag: {
        deal: ['No comment on the specifics, but watch this space.'],
        rumor: ['We will address speculation through the right channels.'],
      },
    },
    meme_account: {
      generic: ['screenshotting this 📸', 'pop twitter in shambles rn', 'the timeline is not ready for this'],
      byTag: {
        big_moment: ['{player} really said "watch this" 💀', 'ratio incoming for anyone who disagrees'],
        loss: ['this fanbase rn: 💀', 'the replies are NOT kind'],
        controversial: ['grab the popcorn 🍿', 'this is going to be a whole thing'],
      },
    },
    match_reporter: {
      generic: ['Noted for the column.', 'Will have more analysis on this shortly.'],
      byTag: {
        big_moment: ['That chorus will be replayed on playlists for weeks.'],
        huge_moment: ['A chart-topping run that deserves real recognition. Full piece incoming.'],
        setback: ['Will follow up with the label for an official update on this.'],
      },
    },
    insider: {
      generic: ['Watching this space. 👀', 'More on this soon.'],
      byTag: {
        rumor: ['Sources say this is worth monitoring closely. 🎶'],
        deal: ['Talks are said to be at an early stage. Nothing concrete yet.'],
      },
    },
    tabloid: {
      generic: ['the DMs are FLOODED after this one', 'you will not believe the reaction to this'],
      byTag: {
        party: ['spotted 👀 more photos on our site', 'the after-party that has everyone talking'],
        controversial: ['the internet has thoughts and we have receipts', 'this aged... interestingly'],
        relationship: ['well well well 👀', 'the rumour mill just got louder'],
      },
    },
  },

  keywordRules: [
    { tag: 'huge_moment', patterns: [/number one/i, /#1\b/i, /sold out arena/i, /diamond/i] },
    { tag: 'big_moment', patterns: [/new single/i, /music video/i, /went viral/i, /\bcharted\b/i, /sold out/i] },
    { tag: 'win', patterns: [/\bwon\b/i, /\baward\b/i, /\bvictory\b/i] },
    { tag: 'loss', patterns: [/\bflopped\b/i, /\bbombed\b/i] },
    { tag: 'rivalry', patterns: [/\bfeud\b/i, /\bbeef\b/i, /\bshade\b/i] },
    { tag: 'setback', patterns: [/lost my voice/i, /vocal (strain|rest)/i, /cancel(l)?ed the tour/i] },
    { tag: 'rumor', patterns: [/leaving the label/i, /new label/i, /solo career/i] },
    { tag: 'deal', patterns: [/\bsigned\b/i, /new deal/i, /\bcontract\b/i, /endorsement/i] },
    { tag: 'criticism', patterns: [/\bcritics?\b/i, /\breviewers?\b/i] },
    { tag: 'party', patterns: [/\bparty\b/i, /after[- ]party/i, /\bclub\b/i] },
    { tag: 'relationship', patterns: [/\bgirlfriend\b/i, /\bboyfriend\b/i, /\bengaged\b/i, /\bmarried\b/i] },
    { tag: 'apology', patterns: [/\bsorry\b/i, /\bapolog/i] },
    { tag: 'gratitude', patterns: [/\bthank/i, /\bblessed\b/i, /\bgrateful\b/i, /\bproud\b/i] },
    { tag: 'controversial', patterns: [/\bangry\b/i, /\bfurious\b/i, /\bdisgust/i, /\bdisrespect/i] },
  ],
}
